export const bikes = [
	{
		id: 1,
		title: "Honda Activa 5G",
		description: {
			transmission: "Automatic",
			seatingCapacity: "2 Seater",
			fuelType: "Petrol",
		},
		imageSrc: "/images/bikes/bike-1.webp",
		packages: [
			{ duration: "Daily", pricePerDay: 799, distanceIncluded: "100 km" },
			{ duration: "7 days", pricePerDay: 749, distanceIncluded: "100 km" },
			{ duration: "15 days", pricePerDay: 699, distanceIncluded: "100 km" },
			{ duration: "Monthly", pricePerDay: 649, distanceIncluded: "100 km" },
		],
		deposit: 3000,
		makeYear: 2023,
		brand: "Honda",
		branch: "Koramangala",
		locations: [
			{ value: "mumbai", label: "Mumbai" },
			{ value: "delhi", label: "Delhi" },
		],
	},
	{
		id: 2,
		title: "Yamaha Fascino",
		description: {
			transmission: "Gear",
			seatingCapacity: "2 Seater",
			fuelType: "Petrol",
		},
		imageSrc: "/images/bikes/bike-2.webp",
		packages: [
			{ duration: "Daily", pricePerDay: 699, distanceIncluded: "100 km" },
			{ duration: "7 days", pricePerDay: 659, distanceIncluded: "100 km" },
			{ duration: "15 days", pricePerDay: 619, distanceIncluded: "100 km" },
			{ duration: "Monthly", pricePerDay: 599, distanceIncluded: "100 km" },
		],
		deposit: 2500,
		makeYear: 2022,
		brand: "Yamaha",
		branch: "Indiranagar",
		locations: [
			{ value: "mumbai", label: "Mumbai" },
			{ value: "chennai", label: "Chennai" },
		],
	},
	{
		id: 3,
		title: "Royal Enfield Classic 350",
		description: {
			transmission: "Manual",
			seatingCapacity: "2 Seater",
			fuelType: "Petrol",
		},
		imageSrc: "/images/bikes/bike-3.webp",
		packages: [
			{ duration: "Daily", pricePerDay: 1199, distanceIncluded: "150 km" },
			{ duration: "7 days", pricePerDay: 1099, distanceIncluded: "150 km" },
			{ duration: "15 days", pricePerDay: 999, distanceIncluded: "150 km" },
			{ duration: "Monthly", pricePerDay: 949, distanceIncluded: "150 km" },
		],
		deposit: 5000,
		makeYear: 2021,
		brand: "Royal Enfield",
		branch: "HSR Layout",
		locations: [
			{ value: "bangalore", label: "Bangalore" },
			{ value: "pune", label: "Pune" },
		],
	},
	{
		id: 4,
		title: "Bajaj Pulsar NS200",
		description: {
			transmission: "Manual",
			seatingCapacity: "2 Seater",
			fuelType: "Petrol",
		},
		imageSrc: "/images/bikes/bike-4.webp",
		packages: [
			{ duration: "Daily", pricePerDay: 899, distanceIncluded: "120 km" },
			{ duration: "7 days", pricePerDay: 849, distanceIncluded: "120 km" },
			{ duration: "15 days", pricePerDay: 799, distanceIncluded: "120 km" },
			{ duration: "Monthly", pricePerDay: 749, distanceIncluded: "120 km" },
		],
		deposit: 4000,
		makeYear: 2022,
		brand: "Bajaj",
		branch: "Jayanagar",
		locations: [
			{ value: "hyderabad", label: "Hyderabad" },
			{ value: "chennai", label: "Chennai" },
		],
	},
	{
		id: 5,
		title: "KTM Duke 250",
		description: {
			transmission: "Manual",
			seatingCapacity: "2 Seater",
			fuelType: "Petrol",
		},
		imageSrc: "/images/bikes/bike-5.webp",
		packages: [
			{ duration: "Daily", pricePerDay: 1499, distanceIncluded: "200 km" },
			{ duration: "7 days", pricePerDay: 1399, distanceIncluded: "200 km" },
			{ duration: "15 days", pricePerDay: 1299, distanceIncluded: "200 km" },
			{ duration: "Monthly", pricePerDay: 1199, distanceIncluded: "200 km" },
		],
		deposit: 6000,
		makeYear: 2023,
		brand: "KTM",
		branch: "Whitefield",
		locations: [
			{ value: "bangalore", label: "Bangalore" },
			{ value: "mumbai", label: "Mumbai" },
		],
	},
];
